### PR TITLE
[release-1.2] Bump Contour to v1.19.1

### LINKED ISSUE #648: Bump to latest Contour 1.19.x
Latest release at the moment is [Contour v1.19.1](https://github.com/projectcontour/contour/releases/tag/v1.19.1)

### PR DESCRIPTION
**Pull request by carlisia**
Closes #648.

### CODE REVIEW

**Comment by carlisia** [comment]
/hold

Opened this to ensure there'll no version compatibility issues.

Going over the list of changes to see if we want to port anything.

**Comment by dprotaso** [comment]
`go.mod` needs to be updated

https://github.com/knative-sandbox/net-contour/blob/35a6137fe02a0c064de6bc5ea946b85479e62deb/go.mod#L8

We might also be able to drop the replace directive now
https://github.com/knative-sandbox/net-contour/blob/35a6137fe02a0c064de6bc5ea946b85479e62deb/go.mod#L19

**Comment by dprotaso** [comment]
split has been pretty flakey - made an issue here: https://github.com/knative-sandbox/net-contour/issues/699

**Pull request merged**
