### PR TITLE
[master] Upgrade to latest dependencies

### PR DESCRIPTION
**Pull request by mattmoor**
Produced via:
```shell
./hack/update-deps.sh --upgrade
./hack/update-codegen.sh
```
/cc tcnghia n3wscott
/assign tcnghia n3wscott

### CODE REVIEW

**Review by tcnghia — APPROVED** [review]
/lgtm

**Comment by tcnghia** [comment]
Many failures due to 
```
    interface.go:50: Error loading client config error invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```

**Comment by mattmoor** [comment]
@n3wscott broke stuff.

**Pull request closed without merging**
