### PR TITLE
Fixes #204 - actually parse the correct property & fix the unit tests

### LINKED ISSUE #204: Not parsing Default TLS Secret
Hello, I am trying to use the new feature for the default TLS certificate but it looks it not parsing it correctly after I edit the configmap.

```
kubectl patch cm config-contour -n knative-serving -p '{"data":{"default-tls-secret":"contour-external/default-cert"}}'
```

In my logs `DefaultTLSSecret` remains `nil`

```
contour-ingress-controller-7d8dc96858-9kklz controller {"level":"info","ts":"2020-08-13T09:10:47.360Z","logger":"contour-ingress-controller.config-store","caller":"configmap/store.go:154","msg":"ingress config \"config-contour\" config was added or updated: &config.Contour{VisibilityKeys:map[v1alpha1.IngressVisibility]sets.String{\"ClusterLocal\":sets.String{\"contour-internal/envoy\":sets.Empty{}}, \"ExternalIP\":sets.String{\"contour-external/envoy\":sets.Empty{}}}, VisibilityClasses:map[v1alpha1.IngressVisibility]string{\"ClusterLocal\":\"contour-internal\", \"ExternalIP\":\"contour-external\"}, DefaultTLSSecret:(*types.NamespacedName)(nil)}"}
```

Am I doing anything wrong ?

### PR DESCRIPTION
**Pull request by dprotaso**
Fixes #204

### CODE REVIEW

**Comment by dprotaso** [comment]
accidentally pushed my local `vendor/knative.dev/test-infra` changes (so I could run them on OS X)  - should be good now

**Comment by dprotaso** [comment]
sigh `commit -a` trouble lol

**Comment by dprotaso** [comment]
@mattmoor I'm not an approver ;)

**Comment by mattmoor** [comment]
/approve

Do you want to be? 😉

**Comment by dprotaso** [comment]
> Do you want to be? 😉

gotta earn it 🤣

**Pull request merged**
