### PR TITLE
Add the correct labels to the TLSCertificateDelegation resource

### PR DESCRIPTION
**Pull request by houshengbo**
# Changes

- The TLSCertificateDelegation resource `knative-serving-certs` does not have any label. This PR adds the labels for it.

/kind <kind>

Fixes #

**Release Note**

```release-note

```

**Docs**

```docs

```

### CODE REVIEW

**Review by psschwei — COMMENTED** [review]
/lgtm
/approve

**Comment by houshengbo** [comment]
@evankanderson @dprotaso

**Pull request merged**
