### PR TITLE
Bump k8s version in KinD

### PR DESCRIPTION
**Pull request by nak3**
As per title, this patch bumps k8s version in KinD.

1.21 is no longer supported and auto upgrade keeps failing as https://github.com/knative-sandbox/net-contour/pull/749.

### CODE REVIEW

**Comment by nak3** [comment]
DNS on k8s 1.23.5 has some issue :thinking: All other net-* repo also failed with the same reason.

```
lookup ingress-conformance-0-visibility-oyseiiab.serving-tests.svc.c2164723487.local on 10.96.0.10:53: server misbehaving
```

**Comment by nak3** [comment]
Strange... k8s 1.23.5 with KinD 0.11.1 does not have the issue. Opened https://github.com/knative/networking/issues/660

**Review by psschwei — COMMENTED** [review]
/lgtm

**Pull request merged**
