### PR TITLE
Integrate the gopath hacks

### LINKED ISSUE #372: Use GOPATH hacks to codegen anywhere.
Please see https://github.com/knative/eventing/pull/4621 or https://github.com/knative/serving/pull/10245 for an example.

### PR DESCRIPTION
**Pull request by arghya88**
Signed-off-by: Arghya Sadhu <arghya88@gmail.com>

# Changes

- Use GOPATH hacks to codegen anywhere

Fixes #372

**Release Note**

```release-note

```

**Docs**

```docs

```

### CODE REVIEW

**Review by n3wscott — COMMENTED** [review]
/lgtm
/approve

**Review by tcnghia — APPROVED** [review]

**Pull request merged**
