### PR TITLE
Updates for deprecated network dependencies

### PR DESCRIPTION
**Pull request by psschwei**
Signed-off-by: Paul S. Schweigert <paulschw@us.ibm.com>

Fixes deprecations from networking/pkg refactor : https://github.com/knative/networking/pull/670

### CODE REVIEW

**Comment by dprotaso** [comment]
blah sorry - thought update deps would merge after this

**Comment by carlisia** [comment]
Thanks for doing this @psschwei!

/lgtm
/approve

**Comment by carlisia** [comment]
Oh, rebase.

**Comment by nak3** [comment]
/lgtm

Thank you! And sorry for the delay to review :sweat:

**Pull request merged**
