### PR TITLE
bump contour to 1.13.1

### PR DESCRIPTION
**Pull request by dprotaso**
# Changes

- :broom:  [Update contour to 1.13.1 ](https://github.com/projectcontour/contour/releases/tag/v1.13.1)
  - Notable fix: fixes an issue where changes to the Envoy load balancer address were not immediately being reflected in HTTPProxies' status.

/kind bug

**Release Note**

```release-note
Bump contour to 1.13.1
```

**Docs**

```docs
NONE
```

### CODE REVIEW

**Comment by dprotaso** [comment]
/hold 

will cycle this a few times

**Review by nak3 — APPROVED** [review]
/lgtm

**Pull request merged**
